# Generated by Django 5.0.7 on 2024-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_customer_customuser_is_engineer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_approver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_contributor",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_editor",
            field=models.BooleanField(default=False),
        ),
    ]
