# Generated by Django 5.0.6 on 2024-06-02 22:33

import a_blog.models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("subtitle", tinymce.models.HTMLField()),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("content", tinymce.models.HTMLField()),
                (
                    "post_image",
                    models.ImageField(
                        blank=True,
                        default="posts/default.jpg",
                        null=True,
                        upload_to=a_blog.models.post_directory_path,
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("published", "Published"),
                            ("updated", "Updated"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
