# Generated by Django 5.0.7 on 2024-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Review", "Review"),
                    ("Published", "Published"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
