# Generated by Django 5.0.6 on 2024-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_services", "0002_helpdeskmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                    ("In Progress", "In Progress"),
                    ("New", "New"),
                ],
                default="new",
                max_length=12,
            ),
        ),
    ]
